version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: mimer-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: mimer_user
      POSTGRESQL_PASSWORD: mimer_password
      POSTGRESQL_DATABASE: mimer_db
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - mimer-network

volumes:
  postgres_data:

networks:
  mimer-network:
    driver: bridge